#!/bin/sh

# Unpin all. Only if you need to clean up old stuff, which, who cares?
# for ki in `ipfs pin ls|cut -d' ' -f1`;do ipfs pin rm -r $ki 2>/dev/null;done

# Recursive add of _ipfs (includes pin). Store new top-level key.
topkey=$(ipfs add -r _ipfs|grep -e '_ipfs$'|cut -d' ' -f2)

# Re-publish under hostID
ipfs name publish ${topkey}
