# Site settings
title: EscPlan
description: >- # this means to ignore newlines until "baseurl:"
  Get out. When it really matters.</br>
  Also on weekends.
baseurl: ""  # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
markdown: kramdown
# plugins:
# - jekyll-feed


# Author Info
author:
  name     : rodin
brand:
  name     : EscPlan
  logo_sm  : /assets/escplan_breve.png
  logo     : /assets/escplan.png
  image    : http://vagabondexpedition.com/wp-content/uploads/2015/06/1024-ve-jeep-on-mountain-side-DSC_5470.jpg
  email    :
  github   : 
  twitter  : 
  linkedin : 
  facebook : 

# Posts default Permalink
permalink: /:title


# Exclude from processing.
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock
