# Site settings
title: EscPlan
description: >- # this means to ignore newlines until "baseurl:"
  Always code as if the guy who ends up maintaining your code
  will be a violeaaaant psychopath who knows where you live.
baseurl: ""  # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
markdown: kramdown
# plugins:
# - jekyll-feed


# Author Info
author:
  name     : rodin
brand:
  name     : EscPlan
  image    : http://vagabondexpedition.com/wp-content/uploads/2015/06/1024-ve-jeep-on-mountain-side-DSC_5470.jpg
  email    : root@escplan.com
  github   : 
  twitter  : 
  linkedin : 
  facebook : 

# Posts default Permalink
permalink: /:title


# Exclude from processing.
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock
